apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  dsm: "10.17.1.5"
  protocol: "iscsi"
  location: "/volume2"
  fsType: "ext4"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
