apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: synology-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: synology-credentials
