apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-auth
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretstore
  target:
    name: synology-csi-auth
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: synology-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: synology-credentials
        property: password
