apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermes-data-pvc
  namespace: hermes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi-retain
  resources:
    requests:
      storage: 5Gi
