apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-initial-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: apps/keycloak
        property: username
    - secretKey: password
      remoteRef:
        key: apps/keycloak
        property: password
