apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  - keycloak-crd-keycloaks.yaml
  - keycloak-crd-realmimports.yaml
  - keycloak-operator.yaml
  - keycloak-instance.yaml
  - httproute.yaml
  - referencegrant.yaml


patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: keycloak
    target:
      kind: ServiceAccount|Role|RoleBinding|Service|Deployment
