- name: Join worker nodes to cluster
  hosts: workers, gpu_workers
  become: true
  vars:
    kubeconfig_exists: false

  tasks:
    - name: Check if already joined
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Verify not already in cluster
      shell: |
        if [ -f /etc/kubernetes/kubelet.conf ]; then
          kubectl --kubeconfig=/etc/kubernetes/kubelet.conf get nodes 2>/dev/null && echo "joined" || echo "not_joined"
        else
          echo "not_joined"
        fi
      register: join_status
      changed_when: false

    - name: Display node status
      debug:
        msg: "Node join status: {{ join_status.stdout }}"

    - name: Join cluster (workers only - no control-plane flag)
      shell: "{{ kubeadm_join_command }}"
      when: join_status.stdout == "not_joined"
      register: join_result

    - name: Display join output
      debug:
        var: join_result.stdout_lines
      when: join_result.changed

- name: Verify all nodes joined
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Wait for nodes to appear in cluster
      shell: kubectl get nodes --no-headers | wc -l
      register: node_count
      until: node_count.stdout | int == 5
      retries: 30
      delay: 10

    - name: Show all nodes
      command: kubectl get nodes
      register: nodes_output

    - name: Display nodes
      debug:
        var: nodes_output.stdout_lines
