- name: Install iSCSI tools on all nodes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Install open-iscsi and multipath tools
      apt:
        name:
          - open-iscsi
          - lsscsi
          - sg3-utils
          - multipath-tools
          - scsitools
        state: present
        update_cache: yes

    - name: Enable and start iscsid
      systemd:
        name: iscsid
        enabled: yes
        state: started

    - name: Enable and start multipathd
      systemd:
        name: multipathd
        enabled: yes
        state: started

    - name: Configure multipath
      copy:
        content: |
          defaults {
            user_friendly_names yes
            find_multipaths yes
          }
        dest: /etc/multipath.conf
        backup: yes
      notify: restart multipathd

  handlers:
    - name: restart multipathd
      systemd:
        name: multipathd
        state: restarted
