apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-runner-secret
  namespace: arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-runner-secret
  data:
    - secretKey: github_app_id
      remoteRef:
        key: apps/github-runner
        property: app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: apps/github-runner
        property: installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: apps/github-runner
        property: private_key
