apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s-storage
    server: 10.17.1.5
  persistentVolumeReclaimPolicy: Retain
