apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/external-secrets/external-secrets/releases/download/v0.17.0/eso-crds.yaml
  - https://github.com/external-secrets/external-secrets/releases/download/v0.17.0/external-secrets.yaml
