apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      # securityContext:
      #   fsGroup: 33
      #   runAsUser: 33
      #   runAsGroup: 33
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 33:33 /etc/linkding/data"]
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.40.0
          ports:
            - containerPort: 9090
          securityContext:
            allowPrivelegeEscalation: false
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
              subPath: data/staging/linkding
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
